import {HERO_BY_THEME_ID,PLAYABLE_HEROES,FACTIONS,ALLIANCES,ALLIANCE_NAMES,displayText,skillHelp} from './theme.mjs'
import {ROLES,SKILLS} from '../../.vuepress/components/sanguo/catalog.mjs'
import {setupView,LORD_HEROES} from './setup.mjs'
import {esc,portrait} from './presentation.mjs'
const identity=(role,extra='')=>`<span class="fs-identity role-${role} ${extra}">${ROLES[role].name}</span>`
export function renderHome(ui){
  const h=HERO_BY_THEME_ID.sunwukong,session=ui.resumeSession
  return `${ui.header()}<main class="fs-entry"><div class="fs-entry-art">${portrait(h,'',true)}<span></span></div><section class="fs-entry-copy"><small>CLASSIC IDENTITY · 单机 / AI</small><h1>众神斗法</h1><p>诸天神话，同桌斗法</p><ol><li><b>01</b>随机抽取身份</li><li><b>02</b>主公先选将并亮出</li><li><b>03</b>其余玩家从各自候选中选将</li><li><b>04</b>发牌，从主公开始行动</li></ol><div class="fs-entry-actions">${session?`<button class="fs-secondary" data-action="resume">${session.kind==='setup'?'继续选将':'继续上局'}</button>`:''}<button class="fs-primary" data-action="start">开始身份局 →</button></div><button class="fs-entry-catalog" data-action="heroes">查看人物图鉴 ↗</button><small class="fs-entry-note">5 人身份局 · ${PLAYABLE_HEROES.length} 名可用武将 · 身份不可自选</small></section></main>`
}
export function renderSetup(ui){
  const v=setupView(ui.setup,0),own=ROLES[v.role],lord=v.players[v.lord],lordHero=lord.heroId&&HERO_BY_THEME_ID[lord.heroId],candidate=HERO_BY_THEME_ID[ui.draftHero]
  const stages=['identity','lord','others','ready'],labels=['抽身份','主公先选','其他选将','准备出战'],at=stages.indexOf(v.stage)
  const title=v.stage==='identity'?'你抽到了'+own.name:v.stage==='lord'?v.lord===0?'主公，请先选择你的武将':'等待主公先选将':v.stage==='others'?v.picked?'你已选定，等待其他玩家':'从你的候选中选择一名武将':'武将已全部选定'
  return `${ui.header()}<main class="fs-setup"><ol class="fs-setup-steps">${labels.map((label,i)=>`<li class="${i===at?'current':i<at?'done':''}"><b>${i+1}</b>${label}</li>`).join('')}</ol>
    <section class="fs-draft-identity">${identity(v.role)}<div><strong>你的身份：${own.name}</strong><p>${own.goal}</p></div><span>${v.lord===0?'你是主公':'主公在 '+v.lord+' 号席'}</span></section>
    <section class="fs-draft-status"><div><small>${v.stage==='identity'?'身份已随机分配':v.stage==='lord'?'主公选定前，其他人不能选将':v.stage==='others'?'各自候选独立，身份仍保持隐藏':'选将完成后才发初始手牌'}</small><h2>${title}</h2></div>${lordHero?`<div class="fs-draft-lord">${portrait(lordHero)}<span><small>主公已亮将</small><b>${lordHero.name}</b></span></div>`:''}</section>
    ${v.stage==='identity'?`<section class="fs-role-reveal-panel"><div class="fs-role-card role-${v.role}"><span>你的身份</span><strong>${own.name}</strong><small>${v.lord===0?'主公身份对所有人公开':'仅你能看到，其他玩家不知道'}</small></div><p>身份已锁定，刷新不会重新抽取。</p></section>`:v.candidates.length&&!v.picked?`<section class="fs-draft-options"><div class="fs-draft-count">随机候选 · ${v.candidates.length} 选 1 <small>${v.lord===0?'3 名主公型 + 2 名随机角色':'当前将池 '+PLAYABLE_HEROES.length+' 人，每人 '+v.candidateCount+' 张独立候选'}</small></div><div class="fs-draft-grid" data-scroll="draft">${v.candidates.map(id=>{const h=HERO_BY_THEME_ID[id];return `<article class="fs-draft-option faction-${h.faction} ${ui.draftHero===id?'selected':''}"><button class="fs-draft-pick" data-action="hero" data-id="${id}" aria-label="选择${h.name}" aria-pressed="${ui.draftHero===id}">${portrait(h)}<span><small>${FACTIONS[h.faction]} · ${ALLIANCE_NAMES[ALLIANCES[h.faction]]} · ${h.hp} 体力</small><strong>${h.name}</strong><i>${Object.values(h.skillNames).join(' · ')}</i></span>${LORD_HEROES.includes(id)?'<b class="fs-lord-type">主公型</b>':''}</button><button class="fs-draft-details" data-action="hero-detail" data-id="${id}">技能说明</button></article>`}).join('')}</div></section>`:`<section class="fs-draft-wait"><b>${v.stage==='ready'?'五席齐备，即将发牌':'请稍候'}</b><p>${v.stage==='ready'?'所有武将已亮出；其他玩家的身份依然隐藏。':v.stage==='lord'?'主公 AI 正在从自己的候选武将中选择。':'其他 AI 正在确认各自的候选武将，不会占用你的候选。'}</p></section>`}
    ${v.stage!=='identity'?`<section class="fs-draft-seats" aria-label="选将进度">${v.players.map(p=>{const h=p.heroId&&HERO_BY_THEME_ID[p.heroId];return `<div class="${p.seat===0?'own':''}${!h&&p.ready?' ready':''}">${h?portrait(h):'<span class="fs-draft-hidden">？</span>'}<div><small>${p.seat===0?'你':p.seat+' 号席'}${p.role?' · '+ROLES[p.role].name:''}</small><strong>${h?h.name:p.ready?'✓ 已选':'选将中…'}</strong></div></div>`}).join('')}</section>`:''}
    <footer class="fs-draft-footer">${candidate&&v.candidates.includes(candidate.id)&&!v.picked?`<p><b>${candidate.name}</b> ${Object.entries(candidate.skillNames).map(([s,n])=>`${n}：${esc(skillHelp(candidate,s))}`).join('　')}</p>`:`<p>${v.stage==='identity'?'确认自己的身份后进入选将。':v.stage==='lord'&&v.lord!==0?'主公完成选将后才会给你发候选武将。':v.stage==='ready'?'初始每人四张手牌，首个回合由主公开始。':v.picked?'选择已经锁定，不会因刷新改变。':'只能从发给你的候选中选择，不能自选身份或任意点将。'}</p>`}
      ${v.stage==='identity'?'<button class="fs-primary" data-action="setup-next">进入选将 →</button>':v.stage==='ready'?'<button class="fs-primary" data-action="setup-begin">立即进入对局 →</button>':v.candidates.length&&!v.picked?`<button class="fs-primary" data-action="draft-pick" ${!v.candidates.includes(ui.draftHero)?'disabled':''}>确认${candidate?'选择 '+candidate.name:'选择武将'}</button>`:'<span class="fs-draft-waiting-label">正在等待其他玩家…</span>'}
    </footer></main>`
}
export function heroGallery(){
  return `<p>人物图鉴只用于查看，实际开局从随机发到手中的候选武将中选择。</p><div class="fs-collection-grid">${Object.values(HERO_BY_THEME_ID).map(h=>`<button data-action="hero-detail" data-id="${h.id}" class="${h.playable?'':'not-ready'}">${portrait(h)}<strong>${h.name}</strong><small>${h.playable?'技能可用':'技能待接入'}</small></button>`).join('')}</div>`
}
