import test from 'node:test'
import assert from 'node:assert/strict'
import {freshState,normalize,act,scoreLook,QUESTS,OUTFITS,SCENES,createWorkshop,matchColor,finishWorkshop,localDay,asset} from '../.vuepress/components/dressup/engine.mjs'
test('fresh state starts with wearable outfit and 100 coins',()=>{const s=freshState();assert.equal(s.coins,100);assert.deepEqual(s.owned,['blush']);assert.equal(asset('blush',2),'/img/games/dressup/blush-2.webp')})
test('insufficient coins and unknown IDs do not change state',()=>{const s=freshState();for(const id of ['night','nope']){const r=act(s,{type:'buy',id});assert.equal(r.ok,false);assert.deepEqual(r.state,s)}})
test('purchase is once-only and cannot spend twice',()=>{let s=freshState();s.coins=500;const r=act(s,{type:'buy',id:'mint'});assert.equal(r.state.coins,360);assert.equal(r.state.look.outfit,'mint');assert.equal(act(r.state,{type:'buy',id:'mint'}).state.coins,360);assert.equal(s.coins,500)})
test('scene purchase and locked equipment checks',()=>{const s=freshState();assert.equal(act(s,{type:'scene',id:'moon'}).ok,false);assert.equal(act(s,{type:'wear',outfit:'ice'}).ok,false);const r=act(s,{type:'buy',kind:'scene',id:'garden'});assert.equal(r.state.coins,40);assert.equal(r.state.look.scene,'garden');assert.equal(act(s,{type:'pose',id:99}).ok,false)})
test('daily reward idempotent and ignores older days',()=>{const s=act(freshState(),{type:'daily',day:'2026-09-29'}).state;assert.equal(s.coins,140);assert.equal(act(s,{type:'daily',day:'2026-09-29'}).state.coins,140);assert.equal(act(s,{type:'daily',day:'2026-09-28'}).ok,false);assert.equal(act(s,{type:'daily',day:'2026-09-30'}).state.coins,180);assert.equal(act(s,{type:'daily',day:'bad'}).ok,false)})
test('quest requires every condition and rewards only once',()=>{let s=freshState();assert.equal(scoreLook(s.look,QUESTS[0]).score,75);assert.equal(act(s,{type:'quest',id:'hello'}).ok,false);s=act(s,{type:'pose',id:2}).state;const r=act(s,{type:'quest',id:'hello'});assert.equal(r.state.coins,200);assert.equal(act(r.state,{type:'quest',id:'hello'}).state.coins,200)})
test('all quests are reachable and catalogue references valid',()=>{const s=freshState();s.owned=OUTFITS.map(x=>x.id);s.scenes=SCENES.map(x=>x.id);for(const q of QUESTS){s.look={outfit:OUTFITS.find(x=>x.tags.includes(q.tag)).id,scene:q.scene,pose:q.pose};assert.equal(act(s,{type:'quest',id:q.id}).ok,true)}})
test('workshop wrong choice has no progress, completion pays exactly once',()=>{let s=freshState(),session=createWorkshop(()=>.3);assert.deepEqual(session.targets,[1,1,1,1,1]);assert.equal(matchColor(session,0).session.step,0);assert.equal(finishWorkshop(s,session).ok,false);for(let i=0;i<5;i++)session=matchColor(session,1).session;const r=finishWorkshop(s,session);assert.equal(r.state.coins,125);assert.equal(r.state.atelierWins,1);assert.equal(finishWorkshop(r.state,r.session).ok,false);assert.equal(matchColor(r.session,1).complete,false)})
test('albums deduplicate, cap at 12 and restore only owned looks',()=>{let s=freshState();s.owned=OUTFITS.map(x=>x.id);s.scenes=SCENES.map(x=>x.id);for(let n=0;n<12;n++){s.look={outfit:OUTFITS[n%5].id,scene:SCENES[Math.floor(n/5)].id,pose:n%3};s=act(s,{type:'album',id:String(n)}).state}assert.equal(s.albums.length,12);assert.equal(act(s,{type:'album',id:'extra'}).ok,false);const r=act(s,{type:'restoreAlbum',id:'0'});assert.equal(r.state.look.outfit,'blush');assert.equal(act(s,{type:'removeAlbum',id:'0'}).state.albums.length,11)})
test('malformed saves cannot equip locked clothes or negative coins',()=>{const s=normalize({version:1,coins:-99,owned:['bogus','mint','mint'],scenes:null,look:{outfit:'ice',scene:'moon',pose:99},claimed:['fake'],albums:[null,{}]});assert.equal(s.coins,0);assert.deepEqual(s.owned,['blush','mint']);assert.deepEqual(s.look,{outfit:'blush',scene:'atelier',pose:0});assert.deepEqual(s.claimed,[]);assert.deepEqual(s.albums,[]);assert.deepEqual(normalize({version:999}),freshState())})
test('serialized saves roundtrip and day uses local date',()=>{const s=act(freshState(),{type:'pose',id:1}).state;assert.deepEqual(normalize(JSON.parse(JSON.stringify(s))),s);assert.equal(localDay(new Date(2026,0,2,12)),'2026-01-02')})
